export const PAGE_SIZE = 10;
export const TYPE_ID = 0;
export const PULL_DOWN_REFRESH_DURATION = 1500; // 下拉刷新
export const DEFAULT_HOUSE_TYPE = 0;  // 不限
export const COMMON_HOUSE_TYPE = 1; // 住宅
export const BUSINESS_HOUSE_TYPE = 2; // 商业
export const INDUSTRY_HOUSE_TYPE = 3; // 工业
export const OTHER_HOUSE_TYPE = 4; // 其他
export const SORT_TIME_TYPE = 1; // 最新发布
export const SORT_BID_TIME_TYPE_ASC = 1; // 拍卖时间从近到远
export const SORT_BID_TIME_TIME_DESC = 2; // 拍卖时间从远到近
export const SORT_PRICE_TYPE_DESC = 1; // 价格从高到低
export const SORT_PRICE_TYPE_ASC = 2; // 价格从低到高
export const SORT_CUT_TYPE_ASC = 1 // 折扣力度从大到小
export const SORT_CUT_TYPE_DESC = 2 // 折扣力度从小到大
