export const FILTER_ZONE_CHANGE = 'FILTER_ZONE_CHANGE';
export const FILTER_SUBWAY_CHANGE = 'FILTER_SUBWAY_CHANGE';
export const FILTER_SUBWAY_NAME_CHANGE = 'FILTER_SUBWAY_NAME_CHANGE';
export const TOGGLE_SCROLL = 'TOGGLE_SCROLL';
export const FILTER_MORE_CHANGE = 'FILTER_MORE_CHANGE';
