export const HOUSEINFO_COURT_URl = 'HOUSEINFO_COURT_URl';
export const HOUSEINFO_GET_BASE_LAYOUT = 'HOUSEINFO_GET_BASE_LAYOUT';
export const HOUSEINFO_GET_COURT_LAYOUT = 'HOUSEINFO_GET_COURT_LAYOUT';
export const HOUSEINFO_GET_AROUND_LAYOUT = 'HOUSEINFO_GET_AROUND_LAYOUT';
